site_name: "Demo Docs"
nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Design:
      - System Architecture: design/system-arch.md
      - Template: template.md

theme:
  name: dracula
  features:
    - navigation.instant
    - navigation.tabs
    - toc.integrate
    - content.code.copy
    - search.suggest

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - tables
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

plugins:
  - search
  - with-pdf:
      output_path: pdf/demo-docs.pdf
      theme: null
  - glightbox
