site_name: "Demo Docs"
# Auto-generate navigation from file structure
nav:
  - Welcome: index.md
  - Getting Started: getting-started.md
  - Design:
      - System Architecture: design/system-arch.md
      - Template: template.md
  - PDF Workflow: pdf-workflow.md

# Show all headers in navigation
# docs_dir: docs

# Enable automatic navigation generation
use_directory_urls: true

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tabs
    - toc.integrate
    - content.code.copy
    - search.suggest
    - navigation.expand
    - navigation.sections
    - navigation.tracking
    - navigation.indexes
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-auto
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to light mode
  highlight:
    theme: [default, slate]

extra_css:
  - stylesheets/catppuccin.css   # Catppuccin Macchiato theme
  - stylesheets/pdf.css          # PDF-specific styles

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - tables
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

plugins:
  - search
  - pdf-export
      output_path: pdfs
