name: Deploy MkDocs

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install MkDocs and dependencies
        run: |
          pip install mkdocs
          pip install mkdocs-material
          pip install mkdocs-with-pdf

      - name: Build MkDocs site
        run: mkdocs build --clean

      - name: Build PDF
        run: mkdocs build --clean --site-dir site --pdf-export

      - name: Upload built site
        uses: actions/upload-artifact@v4
        with:
          name: site
          path: site

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
